// <auto-generated />
using System;
using System.Collections.Generic;
using EcoStep.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoStep.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250121222909_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoStep.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Spain",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Genders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenderName = "Male",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            GenderName = "Female",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            GenderName = "Non-binary",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            GenderName = "Gender fluid",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            GenderName = "Agender",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            GenderName = "Bigender",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            GenderName = "Demiboy",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            GenderName = "DemiGirl",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Álava"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Albacete"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Alicante"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Almería"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Asturias"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Ávila"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Badajoz"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Baleares"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Barcelona"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Burgos"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Cáceres"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Cádiz"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Cantabria"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Castellón"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Ceuta"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Ciudad Real"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Córdoba"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Cuenca"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Girona"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Granada"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Guadalajara"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Guipúzcoa"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Huelva"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Huesca"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Jaén"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "La Coruña"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "La Rioja"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Las Palmas"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "León"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Lleida"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Lugo"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Madrid"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Málaga"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Melilla"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Murcia"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Navarra"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Ourense"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Palencia"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Pontevedra"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Salamanca"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Santa Cruz de Tenerife"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Segovia"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Sevilla"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Soria"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Tarragona"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Teruel"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Toledo"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Valencia"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Valladolid"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Vizcaya"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Zamora"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 1,
                            IsDeleted = false,
                            ProvinceName = "Zaragoza"
                        });
                });

            modelBuilder.Entity("EcoStep.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirebaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Image", b =>
                {
                    b.HasOne("EcoStep.Domain.Models.User", "User")
                        .WithOne("Image")
                        .HasForeignKey("EcoStep.Domain.Models.Image", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Province", b =>
                {
                    b.HasOne("EcoStep.Domain.Models.Country", "Country")
                        .WithMany("Province")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("EcoStep.Domain.Models.User", b =>
                {
                    b.HasOne("EcoStep.Domain.Models.Country", "Country")
                        .WithMany("User")
                        .HasForeignKey("CountryId");

                    b.HasOne("EcoStep.Domain.Models.Gender", "Gender")
                        .WithMany("User")
                        .HasForeignKey("GenderId");

                    b.HasOne("EcoStep.Domain.Models.Province", "Province")
                        .WithMany("User")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Country");

                    b.Navigation("Gender");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Country", b =>
                {
                    b.Navigation("Province");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Gender", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoStep.Domain.Models.Province", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoStep.Domain.Models.User", b =>
                {
                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
